### ISSUE TITLE
use rubyorm out of the docker

### ISSUE THREAD

**Issue by claudiug** [rubyomr-preview/rubyomr-preview#13]
Hi guys,

Is possible that in the near future we will be able to use rubyomr without the docker?
I would love to install via `rvm, rbenv, cruby or make install` :)

**Comment by mstoodle** [comment]
Thanks for the question!

Our team is currently focusing almost 100% on getting the OMR project's initial source code drop ready. We're hoping to get that up on github shortly. You can check out our Eclipse project proposal here, if you're interested: [OMR project proposal @ Eclipse](https://projects.eclipse.org/proposals/omr)

For the parts of the Ruby+OMR Technology Preview that are open in the OMR project, we'll update this project to include the glue code needed to compile those OMR components into CRuby.

At that point you, and everyone else, should be able to build at least those parts of the Ruby+OMR Technology Preview that have been open sourced as part of the OMR project. As more parts go open, we'll again update this project with the glue needed for Ruby+OMR.

That should enable all the options you mentioned.

**Comment by charliegracie** [comment]
You can now download, compile and install the Ruby OMR Preview in your environment of choice :)

**Comment by charliegracie** [comment]
Closing this as all of the source is now available.
