### ISSUE TITLE
News

### ISSUE THREAD

**Issue by Ch4s3** [rubyomr-preview/rubyomr-preview#14]
Any news on what's happening with OMR?

**Comment by mstoodle** [comment]
We're going through "creation review" at the Eclipse foundation and, at the same time, dotting i's and crossing t's to get our initial source code drop into the appropriate form, along with creation for other project materials.

https://projects.eclipse.org/reviews/omr-creation-review

Please feel free to register your interest in this project at that review page :) !

**Comment by Ch4s3** [comment]
Thanks for the update! I'll try to login and register interest later, eclipse's login page is broken at the moment.
