### ISSUE TITLE
Bad performance after enable Jit (compare to stock MRI).

### ISSUE THREAD

**Issue by madper** [rubyomr-preview/rubyomr-preview#16]
Hi,
Not sure if it's the correct place to post my naive performance tesing result. 

My naive testing simply find substring from a big file. (the file is generated by runing `git
 log > log` in linux kernel source tree.)

Here is the test script: 

``` ruby
require "benchmark"
# copied from https://github.com/kanwei/algorithms
def kmp_search(string, substring)
  return nil if string.nil? or substring.nil?

  # create failure function table
  pos = 2
  cnd = 0
  failure_table = [-1, 0]
  while pos < substring.length
    if substring[pos - 1] == substring[cnd]
      failure_table[pos] = cnd + 1
      pos += 1
      cnd += 1
    elsif cnd > 0
      cnd = failure_table[cnd]
    else
      failure_table[pos] = 0
      pos += 1
    end
  end

  m = i = 0
  while m + i < string.length
    if substring[i] == string[m + i]
      i += 1
      return m if i == substring.length
    else
      m = m + i - failure_table[i]
      i = failure_table[i] if i > 0
    end
  end
  return nil
end

time = Benchmark.measure do
  File.readlines('log').each do |line|
    puts line if kmp_search(line, 'rubysrc')
  end
end
puts time
```

With stock cruby 2.3.0 it takes 103 seconds. 
With OMR version ruby (ruby 2.2.3p97 (OMR Preview r1) (2015-04-14) [x86_64-linux]) it takes 161 second. (I only enable jit by `export OMR_JIT_OPTIONS="-Xjit"`)

Here is output after `export OMR_JIT_OPTIONS="-Xjit:verbose"`:

> compiling test.rb:38:block (2 levels) in <main>
> - (cold @ 0x7fde30000034 t=2316545ms  2.710ms) test.rb:38:block (2 levels) in <main>
>   compiling test.rb:4:kmp_search
> - (cold @ 0x7fde30000394 t=2323637ms  6.992ms) test.rb:4:kmp_search

**Comment by charliegracie** [comment]
This is the correct place :)

I will take a look today and update.

**Comment by charliegracie** [comment]
I used the ruby mri git log and I was able to reproduce a similar performance delta. In the Ruby OMR Preview we moved the off heap data into the heap. This puts extra pressure on the heap and cause some degree of fragmentation. If I set the following OMR_GC_OPTIONS="-Xmx128m -Xms128m" and use the same JIT option as you I see a faster time than with stock MRI. When comparing to a stock MRI I used a 2.2 version and not 2.3. 

The time spent in the GC seemed high to me with the default heap settings so I am going to grab some profiles in the next day to see if there is something performing sub optimally.

**Comment by madper** [comment]
Yeah, thanks a lot!
After I export OMR_GC_OPTIONS="-Xmx2048m -Xms2048m"  it takes 94 sec . Much faster than stock MRI 2.3.     :-) 
However I found it's a bit hard to find the best value for GC_OPTIONS. When I set it to 800m the ruby panic with `[FATAL] failed to allocate memory` . 
And when I set it to 1280m it takes 109 sec...

**Comment by charliegracie** [comment]
Automatically tuning the heap settings is something that we still investigating for MRI. It is a balancing act between performance and footprint.

**Comment by madper** [comment]
I see. I appreciate your kindly explanation.     :-)
