### ISSUE TITLE
javascript engine required to run rails

### ISSUE THREAD

**Issue by rservant** [rubyomr-preview/rubyomr-preview#4]
I had to install node.js inside my docker image in order to run a rails hello-world example.  Node.js or some other javascript engine should be provided in the docker image to make it easier/quicker  to run a rails app.

**Comment by charliegracie** [comment]
I just pushed an update to the image that contains Node.js.  @rservant can you verify that it works please?

**Comment by rservant** [comment]
Thank you, it works. Latest docker image allows me to run rails without having to install a javascript engine.
