### ISSUE TITLE
Missing libmysqlclient-dev

### ISSUE THREAD

**Issue by splattael** [rubyomr-preview/rubyomr-preview#6]
In order to `bundle` a Rails app which uses `mysql` gem the package `libmysqlclient-dev` has to be present.

Can you add this missing package? :)

**Comment by charliegracie** [comment]
I just pushed an image with that installed.  Can you verify that it works for you now?  Thanks

**Comment by splattael** [comment]
It bundles like charm!

Thank you <3 :)
